config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'auth/failure', to: redirect('/')

  resources :users, only: [:create]
  resources :sessions, only: [:create, :destroy]
  resources :schedules
  resources :locations
  resources :team_members
end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :locations, join_table: :locations_team_members
  validates :first_name, :last_name, :user, presence: true

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :authenticate_user

  def index
    @team_members = current_user.team_members.order("last_name")
  end

  def new
    @team_member = TeamMember.new
  end

  def create
    params["team_member"]["user_id"] = current_user.id
    @team_member = TeamMember.create(team_member_params)
    respond_to do |format|
      format.js
    end
  end

  def update
    @team_member = TeamMember.find(params[:id])
    @team_member.update_attributes(team_member_params)
  end

  def edit
    @team_member = TeamMember.find(params[:id])
  end

  def destroy
    @team_member = TeamMember.find_by_id(params[:id])
    @team_member.destroy
    respond_to do |format|
      format.html { redirect_to team_members_path }
      format.js
    end
  end

  private

  def team_member_params
    params.require(:team_member).permit(
      :first_name,
      :last_name,
      :user_id
    )
  end
end

app/views/team_members/_edit.html.erb
<div class="modal-header">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <h3><%= "Editing #{@team_member.name}" %></h3>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/team_members/_form.html.erb
<%= form_for @team_member, remote: true do |f| %>
  <ul class="errors"></ul>

  <div class="form-group">
    <%= f.label :first_name, "First Name", class:"control-label" %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name, "Last Name", class:"control-label" %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="modal-footer">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
  </div>
<% end %>

app/views/team_members/_index.html.erb
<div class="container">
  <div class="table-responsive">
    <table class="table table-bordered table-hover table-striped" id="team_member-table">
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Actions</th>
      </tr>
      <% n = 1 %>
      <% @team_members.each do |team_member| %>
        <%= render 'team_member', team_member: team_member %>
      <% end %>
    </table>
  </div>
</div>

app/views/team_members/_new.html.erb
<div class="modal-header">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <h3>Add a Team Member</h3>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/team_members/_save.js.erb
$("ul.errors").html("")
<% if @team_member.errors.any? %>
  <% @team_member.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
  console.log(" ! ");
  console.log("unable to save");
  console.log("")
<% else %>
  $("#team_member-modal").modal("hide");
  $("#team_member-table").append("<%= j render(@team_member) %>")
  console.log("Created team member");
  console.log("");
<% end %>

app/views/team_members/_team_member.html.erb
<tr id="team_member_<%= team_member.id %>">
  <td><%= team_member.first_name %></td>
  <td><%= team_member.last_name %></td>
  <td class='col-md-3'>
    <div class='btn-group' role='group'>
      <%= button_to 'Edit', edit_team_member_path(team_member.id),
        remote: true, method: :get, form: { style: 'display:inline-block;'} ,
        class: 'btn btn-default btn-warning' %>
      <%= button_to "Delete", team_member_path(team_member.id), method: :delete,
        data: {
          confirm: "Are you sure you want to delete #{team_member.name}?" },
          remote: true,
          form: { style: "display:inline-block;" },
          class: "btn btn-default btn-danger" %>
    </div>
  </td>
</tr>

app/views/team_members/create.js.erb
<%= render "save" %>

app/views/team_members/destroy.js.erb
$("#team_member_<%= @team_member.id%>").remove();

app/views/team_members/edit.js.erb
$("#team_member-modal").html("<%= escape_javascript(render 'edit') %>");
$("#team_member-modal").modal("show");

app/views/team_members/index.html.erb
<div class="container">
  <h1>Team Members</h1>
  <div class="well">
    <%= link_to "Add Team Member", new_team_member_path, remote: true, class: "btn btn-primary" %>
    <%= link_to "Manage Schedules", schedules_path, class: "btn btn-primary" %>
    <%= link_to "Manage Locations", locations_path, class: "btn btn-primary" %>
  </div>
</div>
<div class="new-team_member"></div>

<%= render 'index' %>

<div id="team_member-modal" class="modal fade"></div>

app/views/team_members/new.js.erb
$("#team_member-modal").html("<%= escape_javascript(render 'new') %>");
$("#team_member-modal").modal("show");

app/views/team_members/update.js.erb
$("#team_member-modal").modal("hide");
$("#team_member_<%= @team_member.id %>").replaceWith("<%= j render(@team_member) %>");