config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'auth/failure', to: redirect('/')

  resources :users, only: [:create]
  resources :sessions, only: [:create, :destroy]
  resources :schedules
  resources :locations
  resources :team_members
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :history]

  validates :start_date, :end_date, :user_id, :name, :location_id,
            presence: true

  belongs_to :user
  belongs_to :location

  has_many :workdays, dependent: :destroy

  after_create :create_work_days

  def create_work_days
    start_date.upto(end_date) do |date|
      Workday.create(schedule_id: id, work_date: date)
    end
  end

  def slug_candidates
    [
      :name,
      [:name, location.name],
      [:name, location.name, random_string]
    ]
  end

  def random_string
    SecureRandom.urlsafe_base64(10)
  end

  def should_generate_new_friendly_id?
    name_changed? || super
  end

  def work_weeks
    weeks = group_by_weeks
    complete_the_weeks(weeks)
  end

  def complete_the_weeks(weeks)
    completed_weeks = []
    weeks.each do |week|
      complete = CompleteTheWeek.new(week).complete_the_week
      completed_weeks << complete
    end
    completed_weeks
  end

  def group_by_weeks
    workdays.group_by { |date| date.work_date.strftime("%U") }.values
  end
end

app/models/schedule/complete_the_week.rb
# ensure week array account for all seven days of the week
class Schedule
  class CompleteTheWeek
    WEEK_DAYS = {
      sunday: "28/2/2016".to_date,
      monday: "29/2/2016".to_date,
      tuesday: "1/3/2016".to_date,
      wednesday: "2/3/2016".to_date,
      thursday: "3/3/2016".to_date,
      friday: "4/3/2016".to_date,
      saturday: "5/3/2016".to_date
    }

    DAYS = %w(Sunday Monday Tuesday Wednesday Thursday Friday Saturday)

    def initialize(week)
      @week = week
    end

    def complete_the_week
      not_a_full_week? ? complete_week : @week
    end

    def not_a_full_week?
      @week.length != 7
    end

    def complete_week
      missing_days.each do |day|
        missing_day = Workday.new(work_date: WEEK_DAYS[day.downcase.to_sym],
                                  schedule_id: -1)
        @week << missing_day
      end
      order_week_by_week_day
    end

    def order_week_by_week_day
      order = []
      DAYS.each do |day|
        @week.each do |date|
          if date.week_day == day
            order << date
            @week.delete_if { |current_day| current_day.week_day == date }
          end
        end
      end
      order
    end

    def missing_days
      current_days = []
      @week.each { |day| current_days << day.week_day }
      DAYS - current_days
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user
  after_action :verify_authorized, except: [:set_schedule_dates,
                                            :set_start_date, :set_end_date ]

  def index
    @schedules = current_user.schedules.order("name")
    @locations = current_user.locations
    @team_members = current_user.team_members
    authorize Schedule
  end

  def new
    @schedule = Schedule.new
    @locations = current_user.locations
    authorize @schedule
  end

  def create
    params["schedule"]["user_id"] = current_user.id
    set_schedule_dates
    @schedule = Schedule.create(schedule_params)
    authorize @schedule
    respond_to do |format|
      format.js
    end
  end

  def update
    @schedule = Schedule.friendly.find(params[:id])
    authorize @schedule
    set_schedule_dates
    @schedule.update_attributes(schedule_params)
  end

  def show
    @schedule = Schedule.friendly.find(params[:id])
    @work_weeks = @schedule.work_weeks
    authorize @schedule
    if request.path != schedule_path(@schedule)
      redirect_to @schedule, status: :moved_permanently
    end
  end

  def edit
    @schedule = Schedule.friendly.find(params[:id])
    @locations = current_user.locations
    authorize @schedule
  end

  def destroy
    @schedule = Schedule.find_by_id(params[:id])
    authorize @schedule
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_path }
      format.js
    end
  end

  def set_schedule_dates
    set_start_date
    set_end_date
  end

  def set_start_date
    start_date = params["schedule"]["start_date"]
    if start_date.present?
      date_ary = start_date.split(" - ")
      params["schedule"]["start_date"] =
        "#{date_ary[0]}/#{date_ary[1]}/#{date_ary[2]}".to_date
    end
  end

  def set_end_date
    end_date = params["schedule"]["end_date"]
    if end_date.present?
      date_ary = end_date.split(" - ")
      params["schedule"]["end_date"] =
        "#{date_ary[0]}/#{date_ary[1]}/#{date_ary[2]}".to_date
    end
  end

  private

  def schedule_params
    params.require(:schedule).permit(
      :name, :start_date, :end_date, :user_id, :location_id
    )
  end
end

app/views/schedules/_edit.html.erb
<div class="modal-header">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <h3><%= "Editing #{@schedule.name}" %></h3>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/schedules/_form.html.erb
<%= form_for @schedule, remote: true do |f| %>
  <ul class="errors"></ul>

  <div class="form-group">
    <%= f.label :name, "Schedule Name", class:"control-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :location, class: "control-label" %>
    <%= f.collection_select :location_id,
      @locations, :id,
        :name, {},
        { class: "form-control select-picker" } %>
  </div>
  <div class="row" >
    <div class="form-group col-xs-6">
      <%= f.label :start_date, "Start Date", class: "control-label" %>
      <%= f.text_field :start_date,
        class: 'datepicker form-control date',
        id: 'datetimepicker6',
        value: f.object.start_date.try(:strftime, "%d - %B - %Y") %>
    </div>
    <div class="form-group col-xs-6">
      <%= f.label :end_date, "End Date", class: "control-label" %>
      <%= f.text_field :end_date,
        class: 'datepicker form-control date',
        id: 'datetimepicker7',
        value: f.object.end_date.try(:strftime, "%d - %B - %Y") %>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
  </div>
<% end %>

<script type="text/javascript">
    $(function () {
        $('#datetimepicker6').datetimepicker({
            format: 'DD - MMMM - YYYY'
          });
        $('#datetimepicker7').datetimepicker({
            format: 'DD - MMMM - YYYY',
            useCurrent: false
        });
    });
</script>

app/views/schedules/_index.html.erb
<div class="container">
  <div class="table-responsive">
    <table class="table table-bordered table-hover table-striped" id="schedule-table">
      <tr>
        <th>Name</th>
        <th>Location</th>
        <th>Start</th>
        <th>End</th>
        <th>Actions</th>
      </tr>
      <% n = 1 %>
      <% @schedules.each do |schedule| %>
        <%= render 'schedule', schedule: schedule %>
      <% end %>
    </table>
  </div>
</div>

app/views/schedules/_new.html.erb
<div class="modal-header">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <h3>Create Schedule</h3>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/schedules/_save.js.erb
$("ul.errors").html("")
<% if @schedule.errors.any? %>
  <% @schedule.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
  console.log(" ! ");
  console.log("unable to save");
  console.log("")
<% else %>
  $("#schedule-modal").modal("hide");
  $("#schedule-table").append("<%= j render(@schedule) %>");
  console.log("Schedule created!");
  console.log("");
<% end %>

app/views/schedules/_schedule.html.erb
<tr id="schedule_<%= schedule.id %>">
  <td class="col-md-4"><%= schedule.name %></td>
  <td class="col-md-2"><%= schedule.location.name %></td>
  <td class="col-md-1"><%= schedule.start_date %></td>
  <td class="col-md-1"><%= schedule.end_date %></td>
  <td class="col-md-2">
  <div class="btn-group" role="group">
    <%= button_to "View", schedule_path(schedule.id), method: :get,
    form: {style: "display:inline-block;"}, class: "btn btn-default btn-primary" %>
    <%= button_to "Edit", edit_schedule_path(schedule.slug), remote: true, method: :get,
      form: {style: "display:inline-block;"}, class: "btn btn-default btn-warning" %>
    <%= button_to "Delete", schedule_path(schedule.id), method: :delete, remote: true,
      data: {
        confirm: "Are you sure you want to delete #{schedule.name}?" },
        form: {style: "display:inline-block;"}, class: "btn btn-default btn-danger" %>
  </div>
  </td>
</tr>

app/views/schedules/_week.html.erb
<div class="day-number">
  <%= day.work_date.day %>
</div>
<div class="month">
  <%= day.work_date.strftime("%b") %>
</div>

app/views/schedules/_work_week.html.erb
<tr>
  <% week.each do |day| %>
    <% if day.schedule_id == -1 %>
      <td class="day col-sm-1 blank_day"></td>
    <% else %>
      <% if day.work_date.month.even? %>
        <td class="day col-sm-1 even_month" id="<%= day.id %>">
          <%= render "week", day: day %>
        </td>
      <% else %>
        <td class="day col-sm-1 odd_month" id="<%= day.id %>">
          <%= render "week", day: day %>
        </td>
      <% end %>
    <% end %>
  <% end %>
</tr>

app/views/schedules/destroy.js.erb
$("#schedule_<%= @schedule.id%>").remove();

app/views/schedules/edit.js.erb
$("#schedule-modal").html("<%= escape_javascript(render 'edit') %>");
$("#schedule-modal").modal("show");

app/views/schedules/index.html.erb
<div class="container">
  <h1>Schedules</h1>
  <div class="well">
    <% if @locations.present? %>
      <%= link_to "Create Schedule", new_schedule_path, remote: true, class: "btn btn-primary" %>
      <%= link_to "Manage Locations", locations_path, class: "btn btn-primary" %>
      <%= link_to "Manage Team Members", team_members_path, class: "btn btn-primary" %>
    <% else %>
      <%= link_to "Please Add a Location!", locations_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<div class="new-schedule"></div>

</br>

<%= render 'index' %>

<div id="schedule-modal" class="modal fade"></div>

app/views/schedules/new.js.erb
$("#schedule-modal").html("<%= escape_javascript(render 'new') %>");
$("#schedule-modal").modal("show");

app/views/schedules/show.html.erb
<div class="container">
  <div class="well">
    <%= link_to "Back to Schedules", schedules_path, class: "btn btn-primary" %>
  </div>
</div>

<div class="container">
  <h1><%= @schedule.name %></h1>
  <h4>Location: <%= @schedule.location.name %></h4>
  <h5>
    <%= "#{@schedule.start_date.strftime('%a %B %e, %Y')} "%>
    <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
    <%= " #{@schedule.end_date.strftime('%a %B %e, %Y')}" %>
  </h5>
</div>

<div class="container">
  <table class="table table-striped table-bordered table-condensed">
    <tr class="info">
      <th class="text-center">Sunday</th>
      <th class="text-center">Monday</th>
      <th class="text-center">Tuesday</th>
      <th class="text-center">Wednesday</th>
      <th class="text-center">Thursday</th>
      <th class="text-center">Friday</th>
      <th class="text-center">Saturday</th>
    </tr>
    <% @work_weeks.each do |week| %>
      <tr>
        <%= render "work_week", week: week %>
      </tr>
    <% end %>
  </table>
</div>

app/views/schedules/update.js.erb
$("#schedule-modal").modal("hide");
$("#schedule_<%= @schedule.id %>").replaceWith("<%= j render(@schedule) %>");