config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'auth/failure', to: redirect('/')

  resources :users, only: [:create]
  resources :sessions, only: [:create, :destroy]
  resources :schedules
  resources :locations
  resources :team_members
end

app/models/location.rb
class Location < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :history]

  belongs_to :user
  has_many :schedules, dependent: :destroy
  has_and_belongs_to_many :team_members, join_table: :locations_team_members
  validates :name, :user, presence: true

  def slug_candidates
    [
      :name,
      [:name, random_string]
    ]
  end

  def random_string
    SecureRandom.urlsafe_base64(10)
  end

  def should_generate_new_friendly_id?
    name_changed? || super
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user

  def index
    @locations = current_user.locations.order("name")
  end

  def new
    @location = Location.new
  end

  def create
    params["location"]["user_id"] = current_user.id
    @location = Location.create(location_params)
    respond_to do |format|
      format.js
    end
  end

  def update
    @location = Location.friendly.find(params[:id])
    @location.update_attributes(location_params)
  end

  def edit
    @location = Location.friendly.find(params[:id])
  end

  def destroy
    @location = Location.find_by_id(params[:id])
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_path }
      format.js
    end
  end

  private

  def location_params
    params.require(:location).permit(
      :name,
      :user_id
    )
  end
end

app/views/locations/_edit.html.erb
<div class="modal-header">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <h3><%= "Editing #{@location.name}" %></h3>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/locations/_form.html.erb
<%= form_for @location, remote: true do |f| %>
  <ul class="errors"></ul>

  <div class="form-group">
    <%= f.label :name, "Location Name", class:"control-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="modal-footer">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
  </div>
<% end %>

app/views/locations/_index.html.erb
<div class="container">
  <div class="table-responsive">
    <table class="table table-bordered table-hover table-striped" id="location-table">
      <tr>
        <th class="col-md-9">Name</th>
        <th class="col-md-3">Actions</th>
      </tr>
      <% @locations.each do |location| %>
        <%= render 'location', location: location %>
      <% end %>
    </table>
  </div>
</div>

app/views/locations/_location.html.erb
<tr id="location_<%= location.id %>">
  <td><%= location.name %></td>
  <td class='col-md-3'>
    <div class='btn-group' role='group'>
      <%= button_to 'Edit', edit_location_path(location.slug),
        remote: true, method: :get, form: { style: 'display:inline-block;'} ,
        class: 'btn btn-default btn-warning' %>
      <%= button_to "Delete", location_path(location.id), method: :delete,
        data: {
          confirm: "Are you sure you want to delete #{location.name}? \n\n This will delete all schedules with this location too!" },
          remote: true,
          form: { style: "display:inline-block;" },
          class: "btn btn-default btn-danger" %>
    </div>
  </td>
</tr>

app/views/locations/_new.html.erb
<div class="modal-header">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <h3>Add a Location</h3>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/locations/_save.js.erb
$("ul.errors").html("")
<% if @location.errors.any? %>
  <% @location.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
  console.log(" ! ");
  console.log("unable to save");
  console.log("")
<% else %>
  $("#location-modal").modal("hide");
  $("#location-table").append("<%= j render(@location) %>")
  console.log("Location created!");
  console.log("");
<% end %>

app/views/locations/destroy.js.erb
$("#location_<%= @location.id%>").remove();

app/views/locations/edit.js.erb
$("#location-modal").html("<%= escape_javascript(render 'edit') %>");
$("#location-modal").modal("show");

app/views/locations/index.html.erb
<div class="container">
  <h1>Locations</h1>
  <div class="well">
    <%= link_to "Add Location", new_location_path, remote: true, class: "btn btn-primary" %>
    <%= link_to "Manage Schedules", schedules_path, class: "btn btn-primary" %>
    <%= link_to "Manage Team Members", team_members_path, class: "btn btn-primary" %>
  </div>
</div>
<div class="new-location"></div>

<%= render 'index' %>

<div id="location-modal" class="modal fade"></div>

app/views/locations/new.js.erb
$("#location-modal").html("<%= escape_javascript(render 'new') %>");
$("#location-modal").modal("show");

app/views/locations/update.js.erb
$("#location-modal").modal("hide");
$("#location_<%= @location.id %>").replaceWith("<%= j render(@location) %>");